---
- include: create_v2_partitions.yml

- name: Update Environment To Enable Package Installation
  hosts: RHUA:CDS_01:CDS_02
  user: ec2-user
  become: true
  gather_facts: true

  tasks:
    - name: disable rh-common repo
      shell: yum-config-manager --disable rhui-REGION-rhel-server-rh-common

    - name: copy rhui-lb.py
      action: copy src="./files/setup/remote_host/rhui-lb.py" dest="/home/ec2-user/rhui-lb.py" owner=root mode=0644

    - name: update rhui-lb.py
      replace: dest="/home/ec2-user/rhui-lb.py" regexp='REGION' replace='{{ region }}'

    - name: backup original copy of rhui-lb.py
      shell: cp /usr/lib/yum-plugins/rhui-lb.py /usr/lib/yum-plugins/rhui-lb.py.backup

    - name: install new rhui-lb.py
      shell: cp /home/ec2-user/rhui-lb.py /usr/lib/yum-plugins/

- name: Install Common Packages for both RHUA & CDS
  hosts: RHUA:CDS_01:CDS_02
  user: ec2-user
  become: true
  gather_facts: true

  tasks:
    - name: scp sample .rc files over to hosts to make editing easier for root
      action: copy src="files/{{item}}" dest="/root/.{{item}}" owner=root group=root
      with_items:
        - bashrc
        - vimrc

    - name: scp sample .rc files over to hosts to make editing easier for ec2-user
      action: copy src="files/{{item}}" dest="/home/ec2-user/.{{item}}" owner=ec2-user group=ec2-user
      with_items:
        - bashrc
        - vimrc

    - include: tasks/prep_iso_install.yml
      when: iso_path != ""

    - include: tasks/prep_repo_install.yml
      when: iso_path == ""

- name: Install Packages for RHUA
  hosts: RHUA
  user: ec2-user
  become: true
  gather_facts: true

  vars:
    - rhui_build_host: ec2-50-17-26-28.compute-1.amazonaws.com

  tasks:
    - include: tasks/rhua_iso_v2_install_software.yml
      when: iso_path != ""

    - include: tasks/rhua_repo_install_software.yml
      when: iso_path == ""

    - name: restart httpd
      action: service name=httpd state=restarted

- name: Install Packages for CDS
  hosts: CDS_01:CDS_02
  user: ec2-user
  become: true
  gather_facts: true

  vars:
    - rhui_build_host: ec2-50-17-26-28.compute-1.amazonaws.com

  tasks:
    - include: tasks/cds_repo_install_software.yml
      when: iso_path == ""

    - include: tasks/cds_iso_v2_install_software.yml
      when: iso_path != ""
  handlers:
    - name: restart httpd
      action: service name=httpd state=restarted
